### ISSUE TITLE
create a README.md file

### ISSUE THREAD

**Issue by nikitakoselev** [nikitakoselev/EarningMoneyInOpenSource#2]
Can be empty, it's fine.

**Comment by Sandi2212** [comment]
please assign this to me

**Comment by AhVir** [comment]
Hello@nikitakoselev, hope you are doing well. I want to work on this issue. I get the point that I have to create a Markdown file and you also mentioned that it can be empty. But I want to know more about what you will expect within the .md file. 
Also as I'm a beginner to GitHub, OS, and stuff like that, so suggestions are highly appreciated!

**Comment by nikitakoselev** [comment]
> Hello@nikitakoselev, hope you are doing well. I want to work on this issue. I get the point that I have to create a Markdown file and you also mentioned that it can be empty. But I want to know more about what you will expect within the .md file. Also as I'm a beginner to GitHub, OS, and stuff like that, so suggestions are highly appreciated!

Let me give this issue to Sandi2212, as Sandi came first. 

However, your task will be very important too. Please create an "issue" telling that we need a "CONTRIBUTING.md" file.
Also, please, create one more task telling that we need to choose an OpenSource license.
https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue

**Comment by Sandi2212** [comment]
I actually won't be able to pick up this work anymore.. I was assigned another ticket!

**Comment by nikitakoselev** [comment]
Thank you for letting me know, no problems at all :)
Btw, it's a great idea for content creation.
You have honestly shared that you cannot work on the ticket any longer, so I can change the plans now.
Much appreciated.
